import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Duck Classroom</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Duck Classroom
          </h1>
          {session ? (
            <div className="flex flex-col items-center justify-center gap-4">
              <p className="text-2xl font-bold text-white">
                Welcome {session?.user?.name}!
              </p>
              <p className="text-xl font-medium text-white">
                {session?.user?.email}
              </p>

              <button
                className="rounded-md bg-[#2e026d] px-4 py-2 text-lg font-semibold text-white shadow-md hover:bg-[#15162c]"
                onClick={() => signOut()}
              >
                Sign Out
              </button>
            </div>
          ) : (
            <button
              className="rounded-md bg-[#2e026d] px-4 py-2 text-lg font-semibold text-white shadow-md hover:bg-[#15162c]"
              onClick={() => signIn()}
            >
              Sign In
            </button>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
